// shopping types
export default {
  GET_PRODUCT: 'GET_PRODUCT',
  GET_PRODUCT_BY_ID: 'GET_PRODUCT_BY_ID',
  GET_RECENTLY_ADDED_PRODUCTS: 'GET_RECENTLY_ADDED_PRODUCTS',
  GET_PRODUCT_ADD_BY: 'GET_PRODUCT_ADD_BY',
};
